version: '3.8'

services:
  nodejs_test:
    build:
      context: .
      dockerfile: Dockerfile
      target: base

    container_name: nodejs_test

    ports:
      - "3000:80"
      - "9229:9229"
      - "3443:443"

    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

    environment:
      - NODE_ENV=production

    command: npm run start

    networks:
      - default


# Networks
networks:
  default:
    external:
      name: nginx_alan